#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DronMaster
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="Droidika")]
	public partial class DroidikaContextDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertdPolicy(dPolicy instance);
    partial void UpdatedPolicy(dPolicy instance);
    partial void DeletedPolicy(dPolicy instance);
    partial void InsertdPilot1(dPilot1 instance);
    partial void UpdatedPilot1(dPilot1 instance);
    partial void DeletedPilot1(dPilot1 instance);
    partial void InsertdFlightLog(dFlightLog instance);
    partial void UpdatedFlightLog(dFlightLog instance);
    partial void DeletedFlightLog(dFlightLog instance);
    partial void InsertdDrone(dDrone instance);
    partial void UpdatedDrone(dDrone instance);
    partial void DeletedDrone(dDrone instance);
    partial void InsertdCertificate(dCertificate instance);
    partial void UpdatedCertificate(dCertificate instance);
    partial void DeletedCertificate(dCertificate instance);
    partial void InsertdCatDrone1(dCatDrone1 instance);
    partial void UpdatedCatDrone1(dCatDrone1 instance);
    partial void DeletedCatDrone1(dCatDrone1 instance);
    partial void InsertdCatCamera1(dCatCamera1 instance);
    partial void UpdatedCatCamera1(dCatCamera1 instance);
    partial void DeletedCatCamera1(dCatCamera1 instance);
    partial void InsertdAdministrator(dAdministrator instance);
    partial void UpdatedAdministrator(dAdministrator instance);
    partial void DeletedAdministrator(dAdministrator instance);
    partial void InsertdPilot(dPilot instance);
    partial void UpdatedPilot(dPilot instance);
    partial void DeletedPilot(dPilot instance);
    partial void InsertdCatCamera(dCatCamera instance);
    partial void UpdatedCatCamera(dCatCamera instance);
    partial void DeletedCatCamera(dCatCamera instance);
    partial void InsertdCatDrone(dCatDrone instance);
    partial void UpdatedCatDrone(dCatDrone instance);
    partial void DeletedCatDrone(dCatDrone instance);
    #endregion
		
		public DroidikaContextDataContext() : 
				base(global::System.Configuration.ConfigurationManager.ConnectionStrings["DroidikaConnectionString"].ConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public DroidikaContextDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DroidikaContextDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DroidikaContextDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DroidikaContextDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<dPolicy> dPolicies
		{
			get
			{
				return this.GetTable<dPolicy>();
			}
		}
		
		public System.Data.Linq.Table<dPilot1> dPilot1s
		{
			get
			{
				return this.GetTable<dPilot1>();
			}
		}
		
		public System.Data.Linq.Table<dFlightLog> dFlightLogs
		{
			get
			{
				return this.GetTable<dFlightLog>();
			}
		}
		
		public System.Data.Linq.Table<dDrone> dDrones
		{
			get
			{
				return this.GetTable<dDrone>();
			}
		}
		
		public System.Data.Linq.Table<dCertificate> dCertificates
		{
			get
			{
				return this.GetTable<dCertificate>();
			}
		}
		
		public System.Data.Linq.Table<dCatDrone1> dCatDrone1s
		{
			get
			{
				return this.GetTable<dCatDrone1>();
			}
		}
		
		public System.Data.Linq.Table<dCatCamera1> dCatCamera1s
		{
			get
			{
				return this.GetTable<dCatCamera1>();
			}
		}
		
		public System.Data.Linq.Table<dAdministrator> dAdministrators
		{
			get
			{
				return this.GetTable<dAdministrator>();
			}
		}
		
		public System.Data.Linq.Table<dPilot> dPilots
		{
			get
			{
				return this.GetTable<dPilot>();
			}
		}
		
		public System.Data.Linq.Table<dCatCamera> dCatCameras
		{
			get
			{
				return this.GetTable<dCatCamera>();
			}
		}
		
		public System.Data.Linq.Table<dCatDrone> dCatDrones
		{
			get
			{
				return this.GetTable<dCatDrone>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.dPolicies")]
	public partial class dPolicy : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id;
		
		private string _droneAlias;
		
		private string _manufactureYear;
		
		private string _pilotEmail;
		
		private System.Nullable<decimal> _droneValue;
		
		private System.Nullable<decimal> _droneNetPremium;
		
		private System.Nullable<decimal> _civilRes;
		
		private System.Nullable<decimal> _civilNetPremium;
		
		private System.Nullable<decimal> _custDroneNetPremium;
		
		private System.Nullable<decimal> _custCivilNetPremium;
		
		private System.Nullable<int> _durationDays;
		
		private System.Nullable<decimal> _policyPriceUsd;
		
		private System.Nullable<System.DateTime> _policyPurchaseDate;
		
		private System.Nullable<System.DateTime> _policyExpirationDate;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidChanging(int value);
    partial void OnidChanged();
    partial void OndroneAliasChanging(string value);
    partial void OndroneAliasChanged();
    partial void OnmanufactureYearChanging(string value);
    partial void OnmanufactureYearChanged();
    partial void OnpilotEmailChanging(string value);
    partial void OnpilotEmailChanged();
    partial void OndroneValueChanging(System.Nullable<decimal> value);
    partial void OndroneValueChanged();
    partial void OndroneNetPremiumChanging(System.Nullable<decimal> value);
    partial void OndroneNetPremiumChanged();
    partial void OncivilResChanging(System.Nullable<decimal> value);
    partial void OncivilResChanged();
    partial void OncivilNetPremiumChanging(System.Nullable<decimal> value);
    partial void OncivilNetPremiumChanged();
    partial void OncustDroneNetPremiumChanging(System.Nullable<decimal> value);
    partial void OncustDroneNetPremiumChanged();
    partial void OncustCivilNetPremiumChanging(System.Nullable<decimal> value);
    partial void OncustCivilNetPremiumChanged();
    partial void OndurationDaysChanging(System.Nullable<int> value);
    partial void OndurationDaysChanged();
    partial void OnpolicyPriceUsdChanging(System.Nullable<decimal> value);
    partial void OnpolicyPriceUsdChanged();
    partial void OnpolicyPurchaseDateChanging(System.Nullable<System.DateTime> value);
    partial void OnpolicyPurchaseDateChanged();
    partial void OnpolicyExpirationDateChanging(System.Nullable<System.DateTime> value);
    partial void OnpolicyExpirationDateChanged();
    #endregion
		
		public dPolicy()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int id
		{
			get
			{
				return this._id;
			}
			set
			{
				if ((this._id != value))
				{
					this.OnidChanging(value);
					this.SendPropertyChanging();
					this._id = value;
					this.SendPropertyChanged("id");
					this.OnidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_droneAlias", DbType="VarChar(16)")]
		public string droneAlias
		{
			get
			{
				return this._droneAlias;
			}
			set
			{
				if ((this._droneAlias != value))
				{
					this.OndroneAliasChanging(value);
					this.SendPropertyChanging();
					this._droneAlias = value;
					this.SendPropertyChanged("droneAlias");
					this.OndroneAliasChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_manufactureYear", DbType="VarChar(4)")]
		public string manufactureYear
		{
			get
			{
				return this._manufactureYear;
			}
			set
			{
				if ((this._manufactureYear != value))
				{
					this.OnmanufactureYearChanging(value);
					this.SendPropertyChanging();
					this._manufactureYear = value;
					this.SendPropertyChanged("manufactureYear");
					this.OnmanufactureYearChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_pilotEmail", DbType="VarChar(20)")]
		public string pilotEmail
		{
			get
			{
				return this._pilotEmail;
			}
			set
			{
				if ((this._pilotEmail != value))
				{
					this.OnpilotEmailChanging(value);
					this.SendPropertyChanging();
					this._pilotEmail = value;
					this.SendPropertyChanged("pilotEmail");
					this.OnpilotEmailChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_droneValue", DbType="Decimal(10,2)")]
		public System.Nullable<decimal> droneValue
		{
			get
			{
				return this._droneValue;
			}
			set
			{
				if ((this._droneValue != value))
				{
					this.OndroneValueChanging(value);
					this.SendPropertyChanging();
					this._droneValue = value;
					this.SendPropertyChanged("droneValue");
					this.OndroneValueChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_droneNetPremium", DbType="Decimal(10,2)")]
		public System.Nullable<decimal> droneNetPremium
		{
			get
			{
				return this._droneNetPremium;
			}
			set
			{
				if ((this._droneNetPremium != value))
				{
					this.OndroneNetPremiumChanging(value);
					this.SendPropertyChanging();
					this._droneNetPremium = value;
					this.SendPropertyChanged("droneNetPremium");
					this.OndroneNetPremiumChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_civilRes", DbType="Decimal(10,2)")]
		public System.Nullable<decimal> civilRes
		{
			get
			{
				return this._civilRes;
			}
			set
			{
				if ((this._civilRes != value))
				{
					this.OncivilResChanging(value);
					this.SendPropertyChanging();
					this._civilRes = value;
					this.SendPropertyChanged("civilRes");
					this.OncivilResChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_civilNetPremium", DbType="Decimal(10,2)")]
		public System.Nullable<decimal> civilNetPremium
		{
			get
			{
				return this._civilNetPremium;
			}
			set
			{
				if ((this._civilNetPremium != value))
				{
					this.OncivilNetPremiumChanging(value);
					this.SendPropertyChanging();
					this._civilNetPremium = value;
					this.SendPropertyChanged("civilNetPremium");
					this.OncivilNetPremiumChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_custDroneNetPremium", DbType="Decimal(10,2)")]
		public System.Nullable<decimal> custDroneNetPremium
		{
			get
			{
				return this._custDroneNetPremium;
			}
			set
			{
				if ((this._custDroneNetPremium != value))
				{
					this.OncustDroneNetPremiumChanging(value);
					this.SendPropertyChanging();
					this._custDroneNetPremium = value;
					this.SendPropertyChanged("custDroneNetPremium");
					this.OncustDroneNetPremiumChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_custCivilNetPremium", DbType="Decimal(10,2)")]
		public System.Nullable<decimal> custCivilNetPremium
		{
			get
			{
				return this._custCivilNetPremium;
			}
			set
			{
				if ((this._custCivilNetPremium != value))
				{
					this.OncustCivilNetPremiumChanging(value);
					this.SendPropertyChanging();
					this._custCivilNetPremium = value;
					this.SendPropertyChanged("custCivilNetPremium");
					this.OncustCivilNetPremiumChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_durationDays", DbType="Int")]
		public System.Nullable<int> durationDays
		{
			get
			{
				return this._durationDays;
			}
			set
			{
				if ((this._durationDays != value))
				{
					this.OndurationDaysChanging(value);
					this.SendPropertyChanging();
					this._durationDays = value;
					this.SendPropertyChanged("durationDays");
					this.OndurationDaysChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_policyPriceUsd", DbType="Decimal(10,2)")]
		public System.Nullable<decimal> policyPriceUsd
		{
			get
			{
				return this._policyPriceUsd;
			}
			set
			{
				if ((this._policyPriceUsd != value))
				{
					this.OnpolicyPriceUsdChanging(value);
					this.SendPropertyChanging();
					this._policyPriceUsd = value;
					this.SendPropertyChanged("policyPriceUsd");
					this.OnpolicyPriceUsdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_policyPurchaseDate", DbType="Date")]
		public System.Nullable<System.DateTime> policyPurchaseDate
		{
			get
			{
				return this._policyPurchaseDate;
			}
			set
			{
				if ((this._policyPurchaseDate != value))
				{
					this.OnpolicyPurchaseDateChanging(value);
					this.SendPropertyChanging();
					this._policyPurchaseDate = value;
					this.SendPropertyChanged("policyPurchaseDate");
					this.OnpolicyPurchaseDateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_policyExpirationDate", DbType="Date")]
		public System.Nullable<System.DateTime> policyExpirationDate
		{
			get
			{
				return this._policyExpirationDate;
			}
			set
			{
				if ((this._policyExpirationDate != value))
				{
					this.OnpolicyExpirationDateChanging(value);
					this.SendPropertyChanging();
					this._policyExpirationDate = value;
					this.SendPropertyChanged("policyExpirationDate");
					this.OnpolicyExpirationDateChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.dPilots")]
	public partial class dPilot1 : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id;
		
		private string _email;
		
		private string _fstName;
		
		private string _lstName;
		
		private string _password;
		
		private System.Nullable<char> _certificate;
		
		private System.Nullable<System.DateTime> _certificateDate;
		
		private System.Nullable<int> _sinisters;
		
		private System.Nullable<int> _flightTime;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidChanging(int value);
    partial void OnidChanged();
    partial void OnemailChanging(string value);
    partial void OnemailChanged();
    partial void OnfstNameChanging(string value);
    partial void OnfstNameChanged();
    partial void OnlstNameChanging(string value);
    partial void OnlstNameChanged();
    partial void OnpasswordChanging(string value);
    partial void OnpasswordChanged();
    partial void OncertificateChanging(System.Nullable<char> value);
    partial void OncertificateChanged();
    partial void OncertificateDateChanging(System.Nullable<System.DateTime> value);
    partial void OncertificateDateChanged();
    partial void OnsinistersChanging(System.Nullable<int> value);
    partial void OnsinistersChanged();
    partial void OnflightTimeChanging(System.Nullable<int> value);
    partial void OnflightTimeChanged();
    #endregion
		
		public dPilot1()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int id
		{
			get
			{
				return this._id;
			}
			set
			{
				if ((this._id != value))
				{
					this.OnidChanging(value);
					this.SendPropertyChanging();
					this._id = value;
					this.SendPropertyChanged("id");
					this.OnidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_email", DbType="VarChar(50)")]
		public string email
		{
			get
			{
				return this._email;
			}
			set
			{
				if ((this._email != value))
				{
					this.OnemailChanging(value);
					this.SendPropertyChanging();
					this._email = value;
					this.SendPropertyChanged("email");
					this.OnemailChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_fstName", DbType="VarChar(30)")]
		public string fstName
		{
			get
			{
				return this._fstName;
			}
			set
			{
				if ((this._fstName != value))
				{
					this.OnfstNameChanging(value);
					this.SendPropertyChanging();
					this._fstName = value;
					this.SendPropertyChanged("fstName");
					this.OnfstNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_lstName", DbType="VarChar(30)")]
		public string lstName
		{
			get
			{
				return this._lstName;
			}
			set
			{
				if ((this._lstName != value))
				{
					this.OnlstNameChanging(value);
					this.SendPropertyChanging();
					this._lstName = value;
					this.SendPropertyChanged("lstName");
					this.OnlstNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_password", DbType="VarChar(12)")]
		public string password
		{
			get
			{
				return this._password;
			}
			set
			{
				if ((this._password != value))
				{
					this.OnpasswordChanging(value);
					this.SendPropertyChanging();
					this._password = value;
					this.SendPropertyChanged("password");
					this.OnpasswordChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_certificate", DbType="Char(1)")]
		public System.Nullable<char> certificate
		{
			get
			{
				return this._certificate;
			}
			set
			{
				if ((this._certificate != value))
				{
					this.OncertificateChanging(value);
					this.SendPropertyChanging();
					this._certificate = value;
					this.SendPropertyChanged("certificate");
					this.OncertificateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_certificateDate", DbType="Date")]
		public System.Nullable<System.DateTime> certificateDate
		{
			get
			{
				return this._certificateDate;
			}
			set
			{
				if ((this._certificateDate != value))
				{
					this.OncertificateDateChanging(value);
					this.SendPropertyChanging();
					this._certificateDate = value;
					this.SendPropertyChanged("certificateDate");
					this.OncertificateDateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_sinisters", DbType="Int")]
		public System.Nullable<int> sinisters
		{
			get
			{
				return this._sinisters;
			}
			set
			{
				if ((this._sinisters != value))
				{
					this.OnsinistersChanging(value);
					this.SendPropertyChanging();
					this._sinisters = value;
					this.SendPropertyChanged("sinisters");
					this.OnsinistersChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_flightTime", DbType="Int")]
		public System.Nullable<int> flightTime
		{
			get
			{
				return this._flightTime;
			}
			set
			{
				if ((this._flightTime != value))
				{
					this.OnflightTimeChanging(value);
					this.SendPropertyChanging();
					this._flightTime = value;
					this.SendPropertyChanged("flightTime");
					this.OnflightTimeChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.dFlightLogs")]
	public partial class dFlightLog : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id;
		
		private string _pilotEmail;
		
		private string _droneAlias;
		
		private string _positionX;
		
		private string _positionY;
		
		private System.Nullable<int> _droneFlightTime;
		
		private System.Nullable<System.DateTime> _startDate;
		
		private System.Nullable<System.DateTime> _finishDate;
		
		private System.Nullable<decimal> _totalFlighTime;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidChanging(int value);
    partial void OnidChanged();
    partial void OnpilotEmailChanging(string value);
    partial void OnpilotEmailChanged();
    partial void OndroneAliasChanging(string value);
    partial void OndroneAliasChanged();
    partial void OnpositionXChanging(string value);
    partial void OnpositionXChanged();
    partial void OnpositionYChanging(string value);
    partial void OnpositionYChanged();
    partial void OndroneFlightTimeChanging(System.Nullable<int> value);
    partial void OndroneFlightTimeChanged();
    partial void OnstartDateChanging(System.Nullable<System.DateTime> value);
    partial void OnstartDateChanged();
    partial void OnfinishDateChanging(System.Nullable<System.DateTime> value);
    partial void OnfinishDateChanged();
    partial void OntotalFlighTimeChanging(System.Nullable<decimal> value);
    partial void OntotalFlighTimeChanged();
    #endregion
		
		public dFlightLog()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int id
		{
			get
			{
				return this._id;
			}
			set
			{
				if ((this._id != value))
				{
					this.OnidChanging(value);
					this.SendPropertyChanging();
					this._id = value;
					this.SendPropertyChanged("id");
					this.OnidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_pilotEmail", DbType="VarChar(30)")]
		public string pilotEmail
		{
			get
			{
				return this._pilotEmail;
			}
			set
			{
				if ((this._pilotEmail != value))
				{
					this.OnpilotEmailChanging(value);
					this.SendPropertyChanging();
					this._pilotEmail = value;
					this.SendPropertyChanged("pilotEmail");
					this.OnpilotEmailChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_droneAlias", DbType="VarChar(30)")]
		public string droneAlias
		{
			get
			{
				return this._droneAlias;
			}
			set
			{
				if ((this._droneAlias != value))
				{
					this.OndroneAliasChanging(value);
					this.SendPropertyChanging();
					this._droneAlias = value;
					this.SendPropertyChanged("droneAlias");
					this.OndroneAliasChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_positionX", DbType="VarChar(70)")]
		public string positionX
		{
			get
			{
				return this._positionX;
			}
			set
			{
				if ((this._positionX != value))
				{
					this.OnpositionXChanging(value);
					this.SendPropertyChanging();
					this._positionX = value;
					this.SendPropertyChanged("positionX");
					this.OnpositionXChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_positionY", DbType="VarChar(70)")]
		public string positionY
		{
			get
			{
				return this._positionY;
			}
			set
			{
				if ((this._positionY != value))
				{
					this.OnpositionYChanging(value);
					this.SendPropertyChanging();
					this._positionY = value;
					this.SendPropertyChanged("positionY");
					this.OnpositionYChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_droneFlightTime", DbType="Int")]
		public System.Nullable<int> droneFlightTime
		{
			get
			{
				return this._droneFlightTime;
			}
			set
			{
				if ((this._droneFlightTime != value))
				{
					this.OndroneFlightTimeChanging(value);
					this.SendPropertyChanging();
					this._droneFlightTime = value;
					this.SendPropertyChanged("droneFlightTime");
					this.OndroneFlightTimeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_startDate", DbType="Date")]
		public System.Nullable<System.DateTime> startDate
		{
			get
			{
				return this._startDate;
			}
			set
			{
				if ((this._startDate != value))
				{
					this.OnstartDateChanging(value);
					this.SendPropertyChanging();
					this._startDate = value;
					this.SendPropertyChanged("startDate");
					this.OnstartDateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_finishDate", DbType="Date")]
		public System.Nullable<System.DateTime> finishDate
		{
			get
			{
				return this._finishDate;
			}
			set
			{
				if ((this._finishDate != value))
				{
					this.OnfinishDateChanging(value);
					this.SendPropertyChanging();
					this._finishDate = value;
					this.SendPropertyChanged("finishDate");
					this.OnfinishDateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_totalFlighTime", DbType="Decimal(3,2)")]
		public System.Nullable<decimal> totalFlighTime
		{
			get
			{
				return this._totalFlighTime;
			}
			set
			{
				if ((this._totalFlighTime != value))
				{
					this.OntotalFlighTimeChanging(value);
					this.SendPropertyChanging();
					this._totalFlighTime = value;
					this.SendPropertyChanged("totalFlighTime");
					this.OntotalFlighTimeChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.dDrones")]
	public partial class dDrone : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id;
		
		private string _alias;
		
		private string _brand;
		
		private string _model;
		
		private string _img;
		
		private System.Nullable<decimal> _costMx;
		
		private System.Nullable<decimal> _costUsd;
		
		private System.Nullable<int> _flightTime;
		
		private string _manufactureYear;
		
		private string _cameraBrand;
		
		private string _cameraModel;
		
		private string _droneSerial;
		
		private string _cameraSerial;
		
		private string _email;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidChanging(int value);
    partial void OnidChanged();
    partial void OnaliasChanging(string value);
    partial void OnaliasChanged();
    partial void OnbrandChanging(string value);
    partial void OnbrandChanged();
    partial void OnmodelChanging(string value);
    partial void OnmodelChanged();
    partial void OnimgChanging(string value);
    partial void OnimgChanged();
    partial void OncostMxChanging(System.Nullable<decimal> value);
    partial void OncostMxChanged();
    partial void OncostUsdChanging(System.Nullable<decimal> value);
    partial void OncostUsdChanged();
    partial void OnflightTimeChanging(System.Nullable<int> value);
    partial void OnflightTimeChanged();
    partial void OnmanufactureYearChanging(string value);
    partial void OnmanufactureYearChanged();
    partial void OncameraBrandChanging(string value);
    partial void OncameraBrandChanged();
    partial void OncameraModelChanging(string value);
    partial void OncameraModelChanged();
    partial void OndroneSerialChanging(string value);
    partial void OndroneSerialChanged();
    partial void OncameraSerialChanging(string value);
    partial void OncameraSerialChanged();
    partial void OnemailChanging(string value);
    partial void OnemailChanged();
    #endregion
		
		public dDrone()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int id
		{
			get
			{
				return this._id;
			}
			set
			{
				if ((this._id != value))
				{
					this.OnidChanging(value);
					this.SendPropertyChanging();
					this._id = value;
					this.SendPropertyChanged("id");
					this.OnidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_alias", DbType="VarChar(16)")]
		public string alias
		{
			get
			{
				return this._alias;
			}
			set
			{
				if ((this._alias != value))
				{
					this.OnaliasChanging(value);
					this.SendPropertyChanging();
					this._alias = value;
					this.SendPropertyChanged("alias");
					this.OnaliasChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_brand", DbType="VarChar(15)")]
		public string brand
		{
			get
			{
				return this._brand;
			}
			set
			{
				if ((this._brand != value))
				{
					this.OnbrandChanging(value);
					this.SendPropertyChanging();
					this._brand = value;
					this.SendPropertyChanged("brand");
					this.OnbrandChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_model", DbType="VarChar(40)")]
		public string model
		{
			get
			{
				return this._model;
			}
			set
			{
				if ((this._model != value))
				{
					this.OnmodelChanging(value);
					this.SendPropertyChanging();
					this._model = value;
					this.SendPropertyChanged("model");
					this.OnmodelChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_img", DbType="VarChar(100)")]
		public string img
		{
			get
			{
				return this._img;
			}
			set
			{
				if ((this._img != value))
				{
					this.OnimgChanging(value);
					this.SendPropertyChanging();
					this._img = value;
					this.SendPropertyChanged("img");
					this.OnimgChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_costMx", DbType="Decimal(10,2)")]
		public System.Nullable<decimal> costMx
		{
			get
			{
				return this._costMx;
			}
			set
			{
				if ((this._costMx != value))
				{
					this.OncostMxChanging(value);
					this.SendPropertyChanging();
					this._costMx = value;
					this.SendPropertyChanged("costMx");
					this.OncostMxChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_costUsd", DbType="Decimal(10,2)")]
		public System.Nullable<decimal> costUsd
		{
			get
			{
				return this._costUsd;
			}
			set
			{
				if ((this._costUsd != value))
				{
					this.OncostUsdChanging(value);
					this.SendPropertyChanging();
					this._costUsd = value;
					this.SendPropertyChanged("costUsd");
					this.OncostUsdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_flightTime", DbType="Int")]
		public System.Nullable<int> flightTime
		{
			get
			{
				return this._flightTime;
			}
			set
			{
				if ((this._flightTime != value))
				{
					this.OnflightTimeChanging(value);
					this.SendPropertyChanging();
					this._flightTime = value;
					this.SendPropertyChanged("flightTime");
					this.OnflightTimeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_manufactureYear", DbType="VarChar(4)")]
		public string manufactureYear
		{
			get
			{
				return this._manufactureYear;
			}
			set
			{
				if ((this._manufactureYear != value))
				{
					this.OnmanufactureYearChanging(value);
					this.SendPropertyChanging();
					this._manufactureYear = value;
					this.SendPropertyChanged("manufactureYear");
					this.OnmanufactureYearChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_cameraBrand", DbType="VarChar(10)")]
		public string cameraBrand
		{
			get
			{
				return this._cameraBrand;
			}
			set
			{
				if ((this._cameraBrand != value))
				{
					this.OncameraBrandChanging(value);
					this.SendPropertyChanging();
					this._cameraBrand = value;
					this.SendPropertyChanged("cameraBrand");
					this.OncameraBrandChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_cameraModel", DbType="VarChar(30)")]
		public string cameraModel
		{
			get
			{
				return this._cameraModel;
			}
			set
			{
				if ((this._cameraModel != value))
				{
					this.OncameraModelChanging(value);
					this.SendPropertyChanging();
					this._cameraModel = value;
					this.SendPropertyChanged("cameraModel");
					this.OncameraModelChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_droneSerial", DbType="VarChar(100)")]
		public string droneSerial
		{
			get
			{
				return this._droneSerial;
			}
			set
			{
				if ((this._droneSerial != value))
				{
					this.OndroneSerialChanging(value);
					this.SendPropertyChanging();
					this._droneSerial = value;
					this.SendPropertyChanged("droneSerial");
					this.OndroneSerialChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_cameraSerial", DbType="VarChar(100)")]
		public string cameraSerial
		{
			get
			{
				return this._cameraSerial;
			}
			set
			{
				if ((this._cameraSerial != value))
				{
					this.OncameraSerialChanging(value);
					this.SendPropertyChanging();
					this._cameraSerial = value;
					this.SendPropertyChanged("cameraSerial");
					this.OncameraSerialChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_email", DbType="VarChar(40)")]
		public string email
		{
			get
			{
				return this._email;
			}
			set
			{
				if ((this._email != value))
				{
					this.OnemailChanging(value);
					this.SendPropertyChanging();
					this._email = value;
					this.SendPropertyChanged("email");
					this.OnemailChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.dCertificates")]
	public partial class dCertificate : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id;
		
		private string _emailPilot;
		
		private string _emailAdmin;
		
		private System.DateTime _dateCertificate;
		
		private string _URLCertificate;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidChanging(int value);
    partial void OnidChanged();
    partial void OnemailPilotChanging(string value);
    partial void OnemailPilotChanged();
    partial void OnemailAdminChanging(string value);
    partial void OnemailAdminChanged();
    partial void OndateCertificateChanging(System.DateTime value);
    partial void OndateCertificateChanged();
    partial void OnURLCertificateChanging(string value);
    partial void OnURLCertificateChanged();
    #endregion
		
		public dCertificate()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int id
		{
			get
			{
				return this._id;
			}
			set
			{
				if ((this._id != value))
				{
					this.OnidChanging(value);
					this.SendPropertyChanging();
					this._id = value;
					this.SendPropertyChanged("id");
					this.OnidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_emailPilot", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string emailPilot
		{
			get
			{
				return this._emailPilot;
			}
			set
			{
				if ((this._emailPilot != value))
				{
					this.OnemailPilotChanging(value);
					this.SendPropertyChanging();
					this._emailPilot = value;
					this.SendPropertyChanged("emailPilot");
					this.OnemailPilotChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_emailAdmin", DbType="VarChar(30) NOT NULL", CanBeNull=false)]
		public string emailAdmin
		{
			get
			{
				return this._emailAdmin;
			}
			set
			{
				if ((this._emailAdmin != value))
				{
					this.OnemailAdminChanging(value);
					this.SendPropertyChanging();
					this._emailAdmin = value;
					this.SendPropertyChanged("emailAdmin");
					this.OnemailAdminChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_dateCertificate", DbType="DateTime NOT NULL")]
		public System.DateTime dateCertificate
		{
			get
			{
				return this._dateCertificate;
			}
			set
			{
				if ((this._dateCertificate != value))
				{
					this.OndateCertificateChanging(value);
					this.SendPropertyChanging();
					this._dateCertificate = value;
					this.SendPropertyChanged("dateCertificate");
					this.OndateCertificateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_URLCertificate", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string URLCertificate
		{
			get
			{
				return this._URLCertificate;
			}
			set
			{
				if ((this._URLCertificate != value))
				{
					this.OnURLCertificateChanging(value);
					this.SendPropertyChanging();
					this._URLCertificate = value;
					this.SendPropertyChanged("URLCertificate");
					this.OnURLCertificateChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.dCatDrones")]
	public partial class dCatDrone1 : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id;
		
		private string _brand;
		
		private string _model;
		
		private string _img;
		
		private System.Nullable<decimal> _costMx;
		
		private System.Nullable<decimal> _costUsd;
		
		private System.Nullable<int> _flightTime;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidChanging(int value);
    partial void OnidChanged();
    partial void OnbrandChanging(string value);
    partial void OnbrandChanged();
    partial void OnmodelChanging(string value);
    partial void OnmodelChanged();
    partial void OnimgChanging(string value);
    partial void OnimgChanged();
    partial void OncostMxChanging(System.Nullable<decimal> value);
    partial void OncostMxChanged();
    partial void OncostUsdChanging(System.Nullable<decimal> value);
    partial void OncostUsdChanged();
    partial void OnflightTimeChanging(System.Nullable<int> value);
    partial void OnflightTimeChanged();
    #endregion
		
		public dCatDrone1()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int id
		{
			get
			{
				return this._id;
			}
			set
			{
				if ((this._id != value))
				{
					this.OnidChanging(value);
					this.SendPropertyChanging();
					this._id = value;
					this.SendPropertyChanged("id");
					this.OnidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_brand", DbType="VarChar(15)")]
		public string brand
		{
			get
			{
				return this._brand;
			}
			set
			{
				if ((this._brand != value))
				{
					this.OnbrandChanging(value);
					this.SendPropertyChanging();
					this._brand = value;
					this.SendPropertyChanged("brand");
					this.OnbrandChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_model", DbType="VarChar(40)")]
		public string model
		{
			get
			{
				return this._model;
			}
			set
			{
				if ((this._model != value))
				{
					this.OnmodelChanging(value);
					this.SendPropertyChanging();
					this._model = value;
					this.SendPropertyChanged("model");
					this.OnmodelChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_img", DbType="VarChar(100)")]
		public string img
		{
			get
			{
				return this._img;
			}
			set
			{
				if ((this._img != value))
				{
					this.OnimgChanging(value);
					this.SendPropertyChanging();
					this._img = value;
					this.SendPropertyChanged("img");
					this.OnimgChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_costMx", DbType="Decimal(10,2)")]
		public System.Nullable<decimal> costMx
		{
			get
			{
				return this._costMx;
			}
			set
			{
				if ((this._costMx != value))
				{
					this.OncostMxChanging(value);
					this.SendPropertyChanging();
					this._costMx = value;
					this.SendPropertyChanged("costMx");
					this.OncostMxChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_costUsd", DbType="Decimal(10,2)")]
		public System.Nullable<decimal> costUsd
		{
			get
			{
				return this._costUsd;
			}
			set
			{
				if ((this._costUsd != value))
				{
					this.OncostUsdChanging(value);
					this.SendPropertyChanging();
					this._costUsd = value;
					this.SendPropertyChanged("costUsd");
					this.OncostUsdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_flightTime", DbType="Int")]
		public System.Nullable<int> flightTime
		{
			get
			{
				return this._flightTime;
			}
			set
			{
				if ((this._flightTime != value))
				{
					this.OnflightTimeChanging(value);
					this.SendPropertyChanging();
					this._flightTime = value;
					this.SendPropertyChanged("flightTime");
					this.OnflightTimeChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.dCatCameras")]
	public partial class dCatCamera1 : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id;
		
		private string _brand;
		
		private string _model;
		
		private string _img;
		
		private System.Nullable<decimal> _costMx;
		
		private System.Nullable<decimal> _costUsd;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidChanging(int value);
    partial void OnidChanged();
    partial void OnbrandChanging(string value);
    partial void OnbrandChanged();
    partial void OnmodelChanging(string value);
    partial void OnmodelChanged();
    partial void OnimgChanging(string value);
    partial void OnimgChanged();
    partial void OncostMxChanging(System.Nullable<decimal> value);
    partial void OncostMxChanged();
    partial void OncostUsdChanging(System.Nullable<decimal> value);
    partial void OncostUsdChanged();
    #endregion
		
		public dCatCamera1()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int id
		{
			get
			{
				return this._id;
			}
			set
			{
				if ((this._id != value))
				{
					this.OnidChanging(value);
					this.SendPropertyChanging();
					this._id = value;
					this.SendPropertyChanged("id");
					this.OnidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_brand", DbType="VarChar(15)")]
		public string brand
		{
			get
			{
				return this._brand;
			}
			set
			{
				if ((this._brand != value))
				{
					this.OnbrandChanging(value);
					this.SendPropertyChanging();
					this._brand = value;
					this.SendPropertyChanged("brand");
					this.OnbrandChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_model", DbType="VarChar(40)")]
		public string model
		{
			get
			{
				return this._model;
			}
			set
			{
				if ((this._model != value))
				{
					this.OnmodelChanging(value);
					this.SendPropertyChanging();
					this._model = value;
					this.SendPropertyChanged("model");
					this.OnmodelChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_img", DbType="VarChar(100)")]
		public string img
		{
			get
			{
				return this._img;
			}
			set
			{
				if ((this._img != value))
				{
					this.OnimgChanging(value);
					this.SendPropertyChanging();
					this._img = value;
					this.SendPropertyChanged("img");
					this.OnimgChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_costMx", DbType="Decimal(10,2)")]
		public System.Nullable<decimal> costMx
		{
			get
			{
				return this._costMx;
			}
			set
			{
				if ((this._costMx != value))
				{
					this.OncostMxChanging(value);
					this.SendPropertyChanging();
					this._costMx = value;
					this.SendPropertyChanged("costMx");
					this.OncostMxChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_costUsd", DbType="Decimal(10,2)")]
		public System.Nullable<decimal> costUsd
		{
			get
			{
				return this._costUsd;
			}
			set
			{
				if ((this._costUsd != value))
				{
					this.OncostUsdChanging(value);
					this.SendPropertyChanging();
					this._costUsd = value;
					this.SendPropertyChanged("costUsd");
					this.OncostUsdChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.dAdministrators")]
	public partial class dAdministrator : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id;
		
		private string _email;
		
		private string _fstName;
		
		private string _lstName;
		
		private string _password;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidChanging(int value);
    partial void OnidChanged();
    partial void OnemailChanging(string value);
    partial void OnemailChanged();
    partial void OnfstNameChanging(string value);
    partial void OnfstNameChanged();
    partial void OnlstNameChanging(string value);
    partial void OnlstNameChanged();
    partial void OnpasswordChanging(string value);
    partial void OnpasswordChanged();
    #endregion
		
		public dAdministrator()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int id
		{
			get
			{
				return this._id;
			}
			set
			{
				if ((this._id != value))
				{
					this.OnidChanging(value);
					this.SendPropertyChanging();
					this._id = value;
					this.SendPropertyChanged("id");
					this.OnidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_email", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string email
		{
			get
			{
				return this._email;
			}
			set
			{
				if ((this._email != value))
				{
					this.OnemailChanging(value);
					this.SendPropertyChanging();
					this._email = value;
					this.SendPropertyChanged("email");
					this.OnemailChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_fstName", DbType="VarChar(30) NOT NULL", CanBeNull=false)]
		public string fstName
		{
			get
			{
				return this._fstName;
			}
			set
			{
				if ((this._fstName != value))
				{
					this.OnfstNameChanging(value);
					this.SendPropertyChanging();
					this._fstName = value;
					this.SendPropertyChanged("fstName");
					this.OnfstNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_lstName", DbType="VarChar(30) NOT NULL", CanBeNull=false)]
		public string lstName
		{
			get
			{
				return this._lstName;
			}
			set
			{
				if ((this._lstName != value))
				{
					this.OnlstNameChanging(value);
					this.SendPropertyChanging();
					this._lstName = value;
					this.SendPropertyChanged("lstName");
					this.OnlstNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_password", DbType="VarChar(12) NOT NULL", CanBeNull=false)]
		public string password
		{
			get
			{
				return this._password;
			}
			set
			{
				if ((this._password != value))
				{
					this.OnpasswordChanging(value);
					this.SendPropertyChanging();
					this._password = value;
					this.SendPropertyChanged("password");
					this.OnpasswordChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.dPilots")]
	public partial class dPilot : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id;
		
		private string _email;
		
		private string _fstName;
		
		private string _lstName;
		
		private string _password;
		
		private System.Nullable<char> _certificate;
		
		private System.Nullable<System.DateTime> _certificateDate;
		
		private System.Nullable<int> _sinisters;
		
		private System.Nullable<int> _flightTime;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidChanging(int value);
    partial void OnidChanged();
    partial void OnemailChanging(string value);
    partial void OnemailChanged();
    partial void OnfstNameChanging(string value);
    partial void OnfstNameChanged();
    partial void OnlstNameChanging(string value);
    partial void OnlstNameChanged();
    partial void OnpasswordChanging(string value);
    partial void OnpasswordChanged();
    partial void OncertificateChanging(System.Nullable<char> value);
    partial void OncertificateChanged();
    partial void OncertificateDateChanging(System.Nullable<System.DateTime> value);
    partial void OncertificateDateChanged();
    partial void OnsinistersChanging(System.Nullable<int> value);
    partial void OnsinistersChanged();
    partial void OnflightTimeChanging(System.Nullable<int> value);
    partial void OnflightTimeChanged();
    #endregion
		
		public dPilot()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int id
		{
			get
			{
				return this._id;
			}
			set
			{
				if ((this._id != value))
				{
					this.OnidChanging(value);
					this.SendPropertyChanging();
					this._id = value;
					this.SendPropertyChanged("id");
					this.OnidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_email", DbType="VarChar(50)")]
		public string email
		{
			get
			{
				return this._email;
			}
			set
			{
				if ((this._email != value))
				{
					this.OnemailChanging(value);
					this.SendPropertyChanging();
					this._email = value;
					this.SendPropertyChanged("email");
					this.OnemailChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_fstName", DbType="VarChar(30)")]
		public string fstName
		{
			get
			{
				return this._fstName;
			}
			set
			{
				if ((this._fstName != value))
				{
					this.OnfstNameChanging(value);
					this.SendPropertyChanging();
					this._fstName = value;
					this.SendPropertyChanged("fstName");
					this.OnfstNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_lstName", DbType="VarChar(30)")]
		public string lstName
		{
			get
			{
				return this._lstName;
			}
			set
			{
				if ((this._lstName != value))
				{
					this.OnlstNameChanging(value);
					this.SendPropertyChanging();
					this._lstName = value;
					this.SendPropertyChanged("lstName");
					this.OnlstNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_password", DbType="VarChar(12)")]
		public string password
		{
			get
			{
				return this._password;
			}
			set
			{
				if ((this._password != value))
				{
					this.OnpasswordChanging(value);
					this.SendPropertyChanging();
					this._password = value;
					this.SendPropertyChanged("password");
					this.OnpasswordChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_certificate", DbType="Char(1)")]
		public System.Nullable<char> certificate
		{
			get
			{
				return this._certificate;
			}
			set
			{
				if ((this._certificate != value))
				{
					this.OncertificateChanging(value);
					this.SendPropertyChanging();
					this._certificate = value;
					this.SendPropertyChanged("certificate");
					this.OncertificateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_certificateDate", DbType="Date")]
		public System.Nullable<System.DateTime> certificateDate
		{
			get
			{
				return this._certificateDate;
			}
			set
			{
				if ((this._certificateDate != value))
				{
					this.OncertificateDateChanging(value);
					this.SendPropertyChanging();
					this._certificateDate = value;
					this.SendPropertyChanged("certificateDate");
					this.OncertificateDateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_sinisters", DbType="Int")]
		public System.Nullable<int> sinisters
		{
			get
			{
				return this._sinisters;
			}
			set
			{
				if ((this._sinisters != value))
				{
					this.OnsinistersChanging(value);
					this.SendPropertyChanging();
					this._sinisters = value;
					this.SendPropertyChanged("sinisters");
					this.OnsinistersChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_flightTime", DbType="Int")]
		public System.Nullable<int> flightTime
		{
			get
			{
				return this._flightTime;
			}
			set
			{
				if ((this._flightTime != value))
				{
					this.OnflightTimeChanging(value);
					this.SendPropertyChanging();
					this._flightTime = value;
					this.SendPropertyChanged("flightTime");
					this.OnflightTimeChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.dCatCameras")]
	public partial class dCatCamera : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id;
		
		private string _brand;
		
		private string _model;
		
		private string _img;
		
		private System.Nullable<decimal> _costMx;
		
		private System.Nullable<decimal> _costUsd;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidChanging(int value);
    partial void OnidChanged();
    partial void OnbrandChanging(string value);
    partial void OnbrandChanged();
    partial void OnmodelChanging(string value);
    partial void OnmodelChanged();
    partial void OnimgChanging(string value);
    partial void OnimgChanged();
    partial void OncostMxChanging(System.Nullable<decimal> value);
    partial void OncostMxChanged();
    partial void OncostUsdChanging(System.Nullable<decimal> value);
    partial void OncostUsdChanged();
    #endregion
		
		public dCatCamera()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int id
		{
			get
			{
				return this._id;
			}
			set
			{
				if ((this._id != value))
				{
					this.OnidChanging(value);
					this.SendPropertyChanging();
					this._id = value;
					this.SendPropertyChanged("id");
					this.OnidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_brand", DbType="VarChar(15)")]
		public string brand
		{
			get
			{
				return this._brand;
			}
			set
			{
				if ((this._brand != value))
				{
					this.OnbrandChanging(value);
					this.SendPropertyChanging();
					this._brand = value;
					this.SendPropertyChanged("brand");
					this.OnbrandChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_model", DbType="VarChar(40)")]
		public string model
		{
			get
			{
				return this._model;
			}
			set
			{
				if ((this._model != value))
				{
					this.OnmodelChanging(value);
					this.SendPropertyChanging();
					this._model = value;
					this.SendPropertyChanged("model");
					this.OnmodelChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_img", DbType="VarChar(100)")]
		public string img
		{
			get
			{
				return this._img;
			}
			set
			{
				if ((this._img != value))
				{
					this.OnimgChanging(value);
					this.SendPropertyChanging();
					this._img = value;
					this.SendPropertyChanged("img");
					this.OnimgChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_costMx", DbType="Decimal(10,2)")]
		public System.Nullable<decimal> costMx
		{
			get
			{
				return this._costMx;
			}
			set
			{
				if ((this._costMx != value))
				{
					this.OncostMxChanging(value);
					this.SendPropertyChanging();
					this._costMx = value;
					this.SendPropertyChanged("costMx");
					this.OncostMxChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_costUsd", DbType="Decimal(10,2)")]
		public System.Nullable<decimal> costUsd
		{
			get
			{
				return this._costUsd;
			}
			set
			{
				if ((this._costUsd != value))
				{
					this.OncostUsdChanging(value);
					this.SendPropertyChanging();
					this._costUsd = value;
					this.SendPropertyChanged("costUsd");
					this.OncostUsdChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.dCatDrones")]
	public partial class dCatDrone : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id;
		
		private string _brand;
		
		private string _model;
		
		private string _img;
		
		private System.Nullable<decimal> _costMx;
		
		private System.Nullable<decimal> _costUsd;
		
		private System.Nullable<int> _flightTime;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidChanging(int value);
    partial void OnidChanged();
    partial void OnbrandChanging(string value);
    partial void OnbrandChanged();
    partial void OnmodelChanging(string value);
    partial void OnmodelChanged();
    partial void OnimgChanging(string value);
    partial void OnimgChanged();
    partial void OncostMxChanging(System.Nullable<decimal> value);
    partial void OncostMxChanged();
    partial void OncostUsdChanging(System.Nullable<decimal> value);
    partial void OncostUsdChanged();
    partial void OnflightTimeChanging(System.Nullable<int> value);
    partial void OnflightTimeChanged();
    #endregion
		
		public dCatDrone()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int id
		{
			get
			{
				return this._id;
			}
			set
			{
				if ((this._id != value))
				{
					this.OnidChanging(value);
					this.SendPropertyChanging();
					this._id = value;
					this.SendPropertyChanged("id");
					this.OnidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_brand", DbType="VarChar(15)")]
		public string brand
		{
			get
			{
				return this._brand;
			}
			set
			{
				if ((this._brand != value))
				{
					this.OnbrandChanging(value);
					this.SendPropertyChanging();
					this._brand = value;
					this.SendPropertyChanged("brand");
					this.OnbrandChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_model", DbType="VarChar(40)")]
		public string model
		{
			get
			{
				return this._model;
			}
			set
			{
				if ((this._model != value))
				{
					this.OnmodelChanging(value);
					this.SendPropertyChanging();
					this._model = value;
					this.SendPropertyChanged("model");
					this.OnmodelChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_img", DbType="VarChar(100)")]
		public string img
		{
			get
			{
				return this._img;
			}
			set
			{
				if ((this._img != value))
				{
					this.OnimgChanging(value);
					this.SendPropertyChanging();
					this._img = value;
					this.SendPropertyChanged("img");
					this.OnimgChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_costMx", DbType="Decimal(10,2)")]
		public System.Nullable<decimal> costMx
		{
			get
			{
				return this._costMx;
			}
			set
			{
				if ((this._costMx != value))
				{
					this.OncostMxChanging(value);
					this.SendPropertyChanging();
					this._costMx = value;
					this.SendPropertyChanged("costMx");
					this.OncostMxChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_costUsd", DbType="Decimal(10,2)")]
		public System.Nullable<decimal> costUsd
		{
			get
			{
				return this._costUsd;
			}
			set
			{
				if ((this._costUsd != value))
				{
					this.OncostUsdChanging(value);
					this.SendPropertyChanging();
					this._costUsd = value;
					this.SendPropertyChanged("costUsd");
					this.OncostUsdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_flightTime", DbType="Int")]
		public System.Nullable<int> flightTime
		{
			get
			{
				return this._flightTime;
			}
			set
			{
				if ((this._flightTime != value))
				{
					this.OnflightTimeChanging(value);
					this.SendPropertyChanging();
					this._flightTime = value;
					this.SendPropertyChanged("flightTime");
					this.OnflightTimeChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
